### ISSUE TITLE
Shareable ESLint config

### ISSUE THREAD

**Issue by matejchalk** [code-pushup/eslint-config#1]
As a Code PushUp user, I would like a recommended preset of ESLint rules which I can use for my Code PushUp config. This will also make it easier to create Code PushUp configs for multiple projects. And I would like to pick only the rules that apply to the technologies I'm using.

- [x] code-pushup/eslint-config#2
- [x] create ESLint configuration based on strict ruleset added in code-pushup/cli#198 
- [x] integrate other plugins we commonly use (e.g. angular, rxjs, cypress, jest)
- [x] separate configs based on technology (usage example: `"extends": ["plugin:code-pushup/typescript", "plugin:code-pushup/node", "plugin:code-pushup/vitest"]`)
- [ ] code-pushup/eslint-config#3
- [x] publish to NPM as `@code-pushup/eslint-config`

**Comment by matejchalk** [comment]
Published [`@code-pushup/eslint-config` version `0.1.0`](https://www.npmjs.com/package/@code-pushup/eslint-config/v/0.1.0) 🚀
